# Generated by Django 3.1.3 on 2020-11-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('bio', models.TextField(help_text='Enter a brief description of the blogger', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField()),
                ('description', models.TextField(help_text='Enter the text of the blog post', max_length=1000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogger')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField()),
                ('commenter', models.CharField(help_text='Enter your name', max_length=100)),
                ('text', models.TextField(help_text='Enter your comment', max_length=1000)),
                ('blogpost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogpost')),
            ],
        ),
    ]
