# Generated by Django 3.1.3 on 2020-11-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
